[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flight-pricer"
version = "1.0.0"
authors = [
  { name="J R", email="jrojas537@gmail.com" },
]
description = "A CLI for searching flight prices via the Duffel API."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "click",
    "requests",
    "pyyaml",
    "tabulate",
]

[project.scripts]
flight-pricer = "flight_pricer:cli"
